AppFinal/urls.py
from django.urls import path, include
from AppFinal import views
from django.contrib.auth.views import LogoutView


app_name="AppFinal"

urlpatterns = [
    path("", views.inicio, name="inicio"),
     path("americanasAle", views.americanasAle, name="americanasAle"),
     path ("alemanasChecasAustriacasAle", views.alemanasChecasAustriacasAle, name="alemanasChecasAustriacasAle"),
     path ("belgasFrancesasAle", views.belgasFrancesasAle, name= "belgasFrancesasAle"),
     path ("britanicasAle", views.britanicasAle, name="britanicasAle"),
     path ("internacionalesAle", views.internacionalesAle, name="internacionalesAle"),
     path ("americanasLager", views.americanasLager, name="americanasLager"),
     path ("alemanasChecasAustriacasLager", views.alemanasChecasAustriacasLager, name="alemanasChecasAustriacasLager"),
     path ("internacionalesLager", views.internacionalesLager, name="internacionalesLager"),
     path ("otras", views.otras, name="otras"),
     path ("cargarReceta", views.cargarReceta, name="cargarReceta"),
     path ("mostrarBusquedaReceta", views.mostrarBusquedaReceta, name="mostrarBusquedaReceta"),
     path("busquedaAmericanasAle", views.busquedaAmericanasAle, name="busquedaAmericanasAle"),
     path("buscarAmericanasAle/", views.buscarAmericanasAle),
     path("busquedaAlemanasChecasAustriacasAle", views.busquedaAlemanasChecasAustriacasAle, name="busquedaAlemanasChecasAustriacasAle"),
     path("buscarAlemanasChecasAustriacasAle/", views.buscarAlemanasChecasAustriacasAle),
     path("busquedaBelgasFrancesasAle", views.busquedaBelgasFrancesasAle, name="busquedaBelgasFrancesasAle"),
     path("buscarBelgasFrancesasAle/", views.buscarBelgasFrancesasAle),
     path("busquedaBritanicasAle", views.busquedaBritanicasAle, name="busquedaBritanicasAle"),
     path("buscarBritanicasAle/", views.buscarBritanicasAle),
     path("busquedaInternacionalesAle", views.busquedaInternacionalesAle, name="busquedaInternacionalesAle"),
     path("buscarInternacionalesAle/", views.buscarInternacionalesAle),
     path("busquedaAmericanasLager", views.busquedaAmericanasLager, name="busquedaAmericanasLager"),
     path("buscarAmericanasLager/", views.buscarAmericanasLager),
     path("busquedaAlemanasChecasAustriacasLager", views.busquedaAlemanasChecasAustriacasLager, name="busquedaAlemanasChecasAustriacasLager"),
     path("buscarAlemanasChecasAustriacasLager/", views.buscarAlemanasChecasAustriacasLager),
     path("busquedaInternacionalesLager", views.busquedaInternacionalesLager, name="busquedaInternacionalesLager"),
     path("buscarInternacionalesLager/", views.buscarInternacionalesLager),
     path("busquedaOtras", views.busquedaOtras, name="busquedaOtras"),
     path("buscarOtras/", views.buscarOtras),

     path ("mostrar", views.mostrarReceta, name="mostrarReceta"),
     path ("leerAmericanasAle", views.leerAmericanasAle, name="leerAmericanasAle"),
     path ("leerAlemanasChecasAustriacasAle", views.leerAlemanasChecasAustriacasAle, name="leerAlemanasChecasAustriacasAle"),
     path ("leerBelgasFrancesasAle", views.leerBelgasFrancesasAle, name="leerBelgasFrancesasAle"),
     path ("leerBritanicasAle", views.leerBritanicasAle, name="leerBritanicasAle"),
     path ("leerInternacionalesAle", views.leerInternacionalesAle, name="leerInternacionalesAle"),
     path ("leerAmericanasLager", views.leerAmericanasLager, name="leerAmericanasLager"),
     path ("leerAlemanasChecasAustriacasLager", views.leerAlemanasChecasAustriacasLager, name="leerAlemanasChecasAustriacasLager"),
     path ("leerInternacionalesLager", views.leerInternacionalesLager, name="leerInternacionalesLager"),
     path ("leerOtras", views.leerOtras, name="leerOtras"),
     path ("editarAmericanasAle/<str:americanasAle_nombre>", views.editarAmericanasAle, name="editarAmericanasAle"),
     path ("editarAlemanasChecasAustriacasAle/<str:alemanasChecasAustriacasAle_nombre>/", views.editarAlemanasChecasAustriacasAle, name="editarAlemanasChecasAustriacasAle"),
     path ("editarBelgasFrancesasAle/<str:belgasFrancesasAle_nombre>/", views.editarBelgasFrancesasAle, name="editarBelgasFrancesasAle"),
     path ("editarBritanicasAle/<str:editarBritanicasAle_nombre>", views.editarBritanicasAle, name="editarBritanicasAle"),
     path ("editarInternacionalesAle/<str:editarInternacionalesAle_nombre>", views.editarInternacionalesAle, name="editarInternacionalesAle"),
     path ("editarAmericanasLager/<str:editarAmericanasLager_nombre>", views.editarAmericanasLager, name="editarAmericanasLager"),
     path ("editarAlemanasChecasAustriacasLager/<str:editarAlemanasChecasAustriacasLager_nombre>", views.editarAlemanasChecasAustriacasLager, name="editarAlemanasChecasAustriacasLager"),
     path("editarInternacionalesLager/<str:editarInternacionalesLager_nombre>", views.editarInternacionalesLager, name="editarInternacionalesLager"),
     path ("editarOtras/<str:editarOtras_nombre>", views.editarOtras, name="editarOtras"),
     path ("eliminarAmericanasAle/<americanasAle_nombre>/", views.eliminarAmericanasAle, name="eliminarAmericanasAle"),
     path ("eliminarAlemanasChecasAustriacasAle/<alemanasChecasAustriacasAle_nombre>/", views.eliminarAlemanasChecasAustriacasAle, name="eliminarAlemanasChecasAustriacasAle"),
     path ("eliminarBelgasFrancesasAle/<belgasFrancesasAle_nombre>/", views.eliminarBelgasFrancesasAle, name="eliminarBelgasFrancesasAle"),
     path ("eliminarBritanicasAle/<britanicasAle_nombre>/", views.eliminarBritanicasAle, name="eliminarBritanicasAle"),
     path ("eliminarInternacionalesAle/<internacionalesAle_nombre>/", views.eliminarInternacionalesAle, name="eliminarInternacionalesAle"),
     path ("eliminarAmericanasLager/<americanasLager_nombre>/", views.eliminarAmericanasLager, name="eliminarAmericanasLager"),
     path ("eliminarAlemanasChecasAustriacasLager/<alemanasChecasAustriacasLager_nombre>/", views.eliminarAlemanasChecasAustriacasLager, name="eliminarAlemanasChecasAustriacasLager"),
     path ("eliminarInternacionalesLager/<internacionalesLager_nombre>/", views.eliminarInternacionalesLager, name="eliminarInternacionalesLager"),
     path ("eliminarOtras/<otras_nombre>/", views.eliminarOtras, name="eliminarOtras"),

     #path ("login", views.login_request, name="login"),
     #path ("register", views.register, name="register"),
     #path ("logout", LogoutView.as_view(template_name="logout.html"), name="logout"),
     #path ("editarPerfil", views.editarPerfil,  name="editarPerfil"),
     #path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),

     path("acercaDeMi/", views.acercaDeMi, name="acercaDeMi"),

]

AppRegistro/urls.py
from django.urls import path, include
from AppFinal import views
from django.contrib.auth.views import LogoutView


app_name="AppRegistro"

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path ("login", views.login_request, name="login"),
    path ("register", views.register, name="register"),
    path ("logout", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path ("editarPerfil", views.editarPerfil,  name="editarPerfil"),
    path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),

]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("AppFinal/", include("AppFinal.urls")),
    path ("AppRegistro/", include("AppRegistro.urls")),
    #path('AppRegistro/', include('AppRegistro.urls', namespace='AppRegistro')),
    #path('AppFinal/', include('AppFinal.urls', namespace='AppFinal')),
] 

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppFinal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from AppFinal.models import AmericanasAle, AlemanasChecasAustriacasAle, BelgasFrancesasAle, BritanicasAle, InternacionalesAle, AmericanasLager, AlemanasChecasAustriacasLager, InternacionalesLager, Otras
from AppFinal.forms import AmericanasAleFormulario, AlemanasChecasAustriacasAleFormulario, BelgasFrancesasAleFormulario, BritanicasAleFormulario, InternacionalesAleFormulario, AmericanasLagerFormulario, AlemanasChecasAustriacasLagerFormulario, InternacionalesLagerFormulario, OtrasFormulario
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.hashers import make_password
from AppRegistro.views import login_request, register, editarPerfil, inicio, User, agregarAvatar, Avatar

# Create your views here.

def inicio(request):
    return render(request, "inicio.html")

@login_required
def inicio(request):
    avatares = Avatar.objects.filter(user=request.user.id)
    url = None
    if avatares:
        url= avatares[0].imagen.url
    return render(request, 'inicio.html', {'url': url})

def americanasAle(request):
    if request.method == 'POST':
        miFormulario = AmericanasAleFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            americanasAle = AmericanasAle(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],
                                          procesoDeCoccion=informacion['proceso_De_Coccion'],
                                          emailDeContacto=informacion["email_De_Contacto"],
                                          fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                          imagen=informacion["imagen"])

            americanasAle.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = AmericanasAleFormulario()
    
    return render(request, 'americanasAle.html', {'miFormulario':miFormulario})




def alemanasChecasAustriacasAle(request):
    if request.method == 'POST':
        miFormulario = AlemanasChecasAustriacasAleFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            alemanasChecasAustriacasAle = AlemanasChecasAustriacasAle(
                                                                    nombre=informacion['nombre'],
                                                                    maltas=informacion['maltas'],
                                                                    lupulo=informacion["lupulo"],
                                                                    levadura=informacion["levadura"],
                                                                    adicionales=informacion["adicionales"],
                                                                    procesoDeCoccion=informacion['proceso_De_Coccion'],
                                                                    emailDeContacto=informacion["email_De_Contacto"],
                                                                    fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                                                    imagen=informacion["imagen"])

            alemanasChecasAustriacasAle.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = AlemanasChecasAustriacasAleFormulario()
    
    return render(request, 'alemanasChecasAustriacasAle.html', {'miFormulario':miFormulario})


def belgasFrancesasAle(request):
    if request.method == 'POST':
        miFormulario = BelgasFrancesasAleFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            belgasFrancesasAle = BelgasFrancesasAle(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],
                                          procesoDeCoccion=informacion['proceso_De_Coccion'],
                                          emailDeContacto=informacion["email_De_Contacto"],
                                          fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                          imagen=informacion["imagen"])

            belgasFrancesasAle.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = BelgasFrancesasAleFormulario()
    
    return render(request, 'belgasFrancesasAle.html', {'miFormulario':miFormulario})


def britanicasAle(request):
    if request.method == 'POST':
        miFormulario = BritanicasAleFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            britanicasAle = BritanicasAle(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],
                                          procesoDeCoccion=informacion['proceso_De_Coccion'],
                                          emailDeContacto=informacion["email_De_Contacto"],
                                          fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                          imagen=informacion["imagen"])

            britanicasAle.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = BritanicasAleFormulario()
    
    return render(request, 'britanicasAle.html', {'miFormulario':miFormulario})


def internacionalesAle(request):
    if request.method == 'POST':
        miFormulario = InternacionalesAleFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            internacionalesAle = InternacionalesAle(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],
                                          procesoDeCoccion=informacion['proceso_De_Coccion'],
                                          emailDeContacto=informacion["email_De_Contacto"],
                                          fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                          imagen=informacion["imagen"])

            internacionalesAle.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = InternacionalesAleFormulario()
    
    return render(request, 'internacionalesAle.html', {'miFormulario':miFormulario})


def americanasLager(request):
    if request.method == 'POST':
        miFormulario = AmericanasLagerFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            americanasLager = AmericanasLager(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],
                                          procesoDeCoccion=informacion['proceso_De_Coccion'],
                                          emailDeContacto=informacion["email_De_Contacto"],
                                          fechaDePublicacion=informacion["fecha_De_Publicacion"],
                                          imagen=informacion["imagen"])

            americanasLager.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = AmericanasLagerFormulario()
    
    return render(request, 'americanasLager.html', {'miFormulario':miFormulario})



def alemanasChecasAustriacasLager(request):
    if request.method == 'POST':
        miFormulario = AlemanasChecasAustriacasLagerFormulario(request.POST, request.FILES)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            alemanasChecasAustriacasLager = AlemanasChecasAustriacasLager(nombre=informacion['nombre'],
                                          maltas=informacion['maltas'],
                                          lupulo=informacion["lupulo"],
                                          levadura=informacion["levadura"],
                                          adicionales=informacion["adicionales"],

AppFinal/templates/leerAlemanasChecasAustriacasAle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


<body>
    <body>
        <li>Alemanas Checas Austriacas Ale</li>
        {% for p in alemanasChecasAustriacasAle %}
            {% if p.nombre %}
            <li> {{p}} </li>
            <li>{% if p.imagen %} 
                     <img src=" {{p.imagen.url}} " alt="mcmd">
                {% endif %}</li>
                <a class="btn btn-primary" href="{% url 'AppFinal:eliminarAlemanasChecasAustriacasAle' p.nombre %}">ELIMINAR RECETA</a>
                <a class="btn btn-primary" href="{% url 'AppFinal:editarAlemanasChecasAustriacasAle'  p.nombre %}">EDITAR RECETA</a>
            </li>
            {% endif %}
        {% endfor %}
<br>

</body>

            <a class="btn btn-primary" href="{% url 'AppFinal:alemanasChecasAustriacasAle' %}">AGREGAR RECETA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                
            </div>
        </div>
    </nav>

{% endblock %}

AppFinal/templates/leerAmericanasAle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <li>Americanas Ale</li>
    {% for p in americanasAle %}
        {% if p.nombre %}
        <li> {{p}} </li>
        <li>    {% if p.imagen %} 
                <img src=" {{p.imagen.url}} " alt="mcmd">
            {% endif %}
        </li>
            <a class="btn btn-primary" href="{% url 'AppFinal:eliminarAmericanasAle' p.nombre %}">ELIMINAR RECETA</a>
            <a class="btn btn-primary" href="{% url 'AppFinal:editarAmericanasAle'  p.nombre %}">EDITAR RECETA</a>
        </li>
        {% endif %}
    {% endfor %}
    


    <br>
    
    <a class="btn btn-primary" href="{% url 'AppFinal:americanasAle' %}">AGREGAR RECETA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
                
    </div>
</body>

{% endblock %}

AppFinal/templates/leerBelgasFrancesasAle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <li>Belgas Francesas Ale</li>
    {% for p in belgasFrancesasAle %}
        {% if p.nombre %}
        <li> {{p}} </li>
        <li>{% if p.imagen %} 
                <img src=" {{p.imagen.url}} " alt="mcmd">
            {% endif %}</li>   
            <a class="btn btn-primary" href="{% url 'AppFinal:eliminarBelgasFrancesasAle' p.nombre %}">ELIMINAR RECETA</a>
            <a class="btn btn-primary" href="{% url 'AppFinal:editarBelgasFrancesasAle'  p.nombre %}">EDITAR RECETA</a>
        </li>
        {% endif %}
    {% endfor %}
    <br>
    <a class="btn btn-primary" href="{% url 'AppFinal:belgasFrancesasAle' %}">AGREGAR RECETA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
                
    </div>
</body>

{% endblock %}

AppFinal/templates/leerBritanicasAle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <li>Britanicas Ale</li>
    {% for p in britanicasAle %}
        {% if p.nombre %}
        <li> {{p}} </li>
        <li>    {% if p.imagen %} 
                 <img src=" {{p.imagen.url}} " alt="mcmd">
            {% endif %}
        </li>
            <a class="btn btn-primary" href="{% url 'AppFinal:eliminarBritanicasAle' p.nombre %}">ELIMINAR RECETA</a>
            <a class="btn btn-primary" href="{% url 'AppFinal:editarBritanicasAle'  p.nombre %}">EDITAR RECETA</a>
        </li>
        {% endif %}
    {% endfor %}

    <br>
    <a class="btn btn-primary" href="{% url 'AppFinal:britanicasAle' %}">AGREGAR RECETA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
                
    </div>
</body>

{% endblock %}

AppFinal/templates/leerInternacionalesAle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <li>Internacionales Ale</li>
    {% for p in internacionalesAle %}
        {% if p.nombre %}
        <li> {{p}} </li>
        <li>    {% if p.imagen %} 
                 <img src=" {{p.imagen.url}} " alt="mcmd">
            {% endif %}
        </li>
            <a class="btn btn-primary" href="{% url 'AppFinal:eliminarInternacionalesAle' p.nombre %}">ELIMINAR RECETA</a>
            <a class="btn btn-primary" href="{% url 'AppFinal:editarInternacionalesAle'  p.nombre %}">EDITAR RECETA</a>
        </li>
        {% endif %}
    {% endfor %}

    <br>
    <a class="btn btn-primary" href="{% url 'AppFinal:internacionalesAle' %}">AGREGAR RECETA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
                
    </div>
</body>

{% endblock %}

AppFinal/templates/leerOtras.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <li>Otras</li>
    {% for p in otras%}
        {% if p.nombre %}
        <li> {{p}} </li>
        <li>    {% if p.imagen %} 
                <img src=" {{p.imagen.url}} " alt="mcmd">
            {% endif %} </li>
            <a class="btn btn-primary" href="{% url 'AppFinal:eliminarOtras' p.nombre %}">ELIMINAR RECETA</a>
            <a class="btn btn-primary" href="{% url 'AppFinal:editarOtras'  p.nombre %}">EDITAR RECETA</a>
        </li>
        {% endif %}
    {% endfor %}

    <br>
    <a class="btn btn-primary" href="{% url 'AppFinal:otras' %}">AGREGAR RECETA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
                
    </div>
</body>

{% endblock %}

AppFinal/templates/mostrarBusquedaReceta.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <h1>BUSCAR RECETAS</h1>
    <p>Elegi el estilo de las recetas que deseas buscar</p>
    <p>ALE</p>
    
                
    <a class="navbar-brand" href="{% url "AppFinal:busquedaAmericanasAle"%}">Americanas Ale</a>
    
    <a class="navbar-brand" href="{% url "AppFinal:busquedaAlemanasChecasAustriacasAle"%}">Alemanas Checas Austriacas Ale</a>


    <a class="navbar-brand" href="{% url "AppFinal:busquedaBelgasFrancesasAle"%}">Belgas Francesas Ale</a>
    <a class="navbar-brand" href="{% url "AppFinal:busquedaBritanicasAle"%}">Britanicas Ale</a>
    <a class="navbar-brand" href="{% url "AppFinal:busquedaInternacionalesAle"%}">Internacionales Ale</a>
        


    
    <p>LAGER</p>

  
                    
    <a class="navbar-brand" href="{% url "AppFinal:busquedaAmericanasLager"%}">Americanas Lager</a>
    <a class="navbar-brand" href="{% url "AppFinal:busquedaAlemanasChecasAustriacasLager"%}">Alemanas Checas Austriacas Lager</a>
    <a class="navbar-brand" href="{% url "AppFinal:busquedaInternacionalesLager"%}">Internacionales Lager</a>
        

    <p>OTRAS</p>

    
    <a class="navbar-brand" href="{% url "AppFinal:busquedaOtras"%}">Otras</a>

{% endblock %}

AppFinal/templates/mostrarReceta.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


    <!--Aquí va lo que cambia, y lo asociado a está vista :) -->
    <h1>MOSTRAR RECETAS</h1>
    <p>Elegi el estilo de las recetas que deseas ver</p>
    <p>ALE</p>
    
                
    <a class="navbar-brand" href="{% url "AppFinal:leerAmericanasAle"%}">Americanas Ale</a>
    
    <a class="navbar-brand" href="{% url "AppFinal:leerAlemanasChecasAustriacasAle"%}">Alemanas Checas Austriacas Ale</a>


    <a class="navbar-brand" href="{% url "AppFinal:leerBelgasFrancesasAle"%}">Belgas Francesas Ale</a>
    <a class="navbar-brand" href="{% url "AppFinal:leerBritanicasAle"%}">Britanicas Ale</a>
    <a class="navbar-brand" href="{% url "AppFinal:leerInternacionalesAle"%}">Internacionales Ale</a>
        


    
    <p>LAGER</p>

  
                    
    <a class="navbar-brand" href="{% url "AppFinal:leerAmericanasLager"%}">Americanas Lager</a>
    <a class="navbar-brand" href="{% url "AppFinal:leerAlemanasChecasAustriacasLager"%}">Alemanas Checas Austriacas Lager</a>
    <a class="navbar-brand" href="{% url "AppFinal:leerInternacionalesLager"%}">Internacionales Lager</a>
        

    <p>OTRAS</p>

    
    <a class="navbar-brand" href="{% url "AppFinal:leerOtras"%}">Otras</a>

{% endblock %}