AppFinal/urls.py
from django.urls import path, include
from AppFinal import views
from django.contrib.auth.views import LogoutView


app_name="AppFinal"

urlpatterns = [
    path("", views.inicio, name="inicio"),
     path("americanasAle", views.americanasAle, name="americanasAle"),
     path ("alemanasChecasAustriacasAle", views.alemanasChecasAustriacasAle, name="alemanasChecasAustriacasAle"),
     path ("belgasFrancesasAle", views.belgasFrancesasAle, name= "belgasFrancesasAle"),
     path ("britanicasAle", views.britanicasAle, name="britanicasAle"),
     path ("internacionalesAle", views.internacionalesAle, name="internacionalesAle"),
     path ("americanasLager", views.americanasLager, name="americanasLager"),
     path ("alemanasChecasAustriacasLager", views.alemanasChecasAustriacasLager, name="alemanasChecasAustriacasLager"),
     path ("internacionalesLager", views.internacionalesLager, name="internacionalesLager"),
     path ("otras", views.otras, name="otras"),
     path ("cargarReceta", views.cargarReceta, name="cargarReceta"),
     path ("mostrarBusquedaReceta", views.mostrarBusquedaReceta, name="mostrarBusquedaReceta"),
     path("busquedaAmericanasAle", views.busquedaAmericanasAle, name="busquedaAmericanasAle"),
     path("buscarAmericanasAle/", views.buscarAmericanasAle),
     path("busquedaAlemanasChecasAustriacasAle", views.busquedaAlemanasChecasAustriacasAle, name="busquedaAlemanasChecasAustriacasAle"),
     path("buscarAlemanasChecasAustriacasAle/", views.buscarAlemanasChecasAustriacasAle),
     path("busquedaBelgasFrancesasAle", views.busquedaBelgasFrancesasAle, name="busquedaBelgasFrancesasAle"),
     path("buscarBelgasFrancesasAle/", views.buscarBelgasFrancesasAle),
     path("busquedaBritanicasAle", views.busquedaBritanicasAle, name="busquedaBritanicasAle"),
     path("buscarBritanicasAle/", views.buscarBritanicasAle),
     path("busquedaInternacionalesAle", views.busquedaInternacionalesAle, name="busquedaInternacionalesAle"),
     path("buscarInternacionalesAle/", views.buscarInternacionalesAle),
     path("busquedaAmericanasLager", views.busquedaAmericanasLager, name="busquedaAmericanasLager"),
     path("buscarAmericanasLager/", views.buscarAmericanasLager),
     path("busquedaAlemanasChecasAustriacasLager", views.busquedaAlemanasChecasAustriacasLager, name="busquedaAlemanasChecasAustriacasLager"),
     path("buscarAlemanasChecasAustriacasLager/", views.buscarAlemanasChecasAustriacasLager),
     path("busquedaInternacionalesLager", views.busquedaInternacionalesLager, name="busquedaInternacionalesLager"),
     path("buscarInternacionalesLager/", views.buscarInternacionalesLager),
     path("busquedaOtras", views.busquedaOtras, name="busquedaOtras"),
     path("buscarOtras/", views.buscarOtras),

     path ("mostrar", views.mostrarReceta, name="mostrarReceta"),
     path ("leerAmericanasAle", views.leerAmericanasAle, name="leerAmericanasAle"),
     path ("leerAlemanasChecasAustriacasAle", views.leerAlemanasChecasAustriacasAle, name="leerAlemanasChecasAustriacasAle"),
     path ("leerBelgasFrancesasAle", views.leerBelgasFrancesasAle, name="leerBelgasFrancesasAle"),
     path ("leerBritanicasAle", views.leerBritanicasAle, name="leerBritanicasAle"),
     path ("leerInternacionalesAle", views.leerInternacionalesAle, name="leerInternacionalesAle"),
     path ("leerAmericanasLager", views.leerAmericanasLager, name="leerAmericanasLager"),
     path ("leerAlemanasChecasAustriacasLager", views.leerAlemanasChecasAustriacasLager, name="leerAlemanasChecasAustriacasLager"),
     path ("leerInternacionalesLager", views.leerInternacionalesLager, name="leerInternacionalesLager"),
     path ("leerOtras", views.leerOtras, name="leerOtras"),
     path ("editarAmericanasAle/<str:americanasAle_nombre>", views.editarAmericanasAle, name="editarAmericanasAle"),
     path ("editarAlemanasChecasAustriacasAle/<str:alemanasChecasAustriacasAle_nombre>/", views.editarAlemanasChecasAustriacasAle, name="editarAlemanasChecasAustriacasAle"),
     path ("editarBelgasFrancesasAle/<str:belgasFrancesasAle_nombre>/", views.editarBelgasFrancesasAle, name="editarBelgasFrancesasAle"),
     path ("editarBritanicasAle/<str:editarBritanicasAle_nombre>", views.editarBritanicasAle, name="editarBritanicasAle"),
     path ("editarInternacionalesAle/<str:editarInternacionalesAle_nombre>", views.editarInternacionalesAle, name="editarInternacionalesAle"),
     path ("editarAmericanasLager/<str:editarAmericanasLager_nombre>", views.editarAmericanasLager, name="editarAmericanasLager"),
     path ("editarAlemanasChecasAustriacasLager/<str:editarAlemanasChecasAustriacasLager_nombre>", views.editarAlemanasChecasAustriacasLager, name="editarAlemanasChecasAustriacasLager"),
     path("editarInternacionalesLager/<str:editarInternacionalesLager_nombre>", views.editarInternacionalesLager, name="editarInternacionalesLager"),
     path ("editarOtras/<str:editarOtras_nombre>", views.editarOtras, name="editarOtras"),
     path ("eliminarAmericanasAle/<americanasAle_nombre>/", views.eliminarAmericanasAle, name="eliminarAmericanasAle"),
     path ("eliminarAlemanasChecasAustriacasAle/<alemanasChecasAustriacasAle_nombre>/", views.eliminarAlemanasChecasAustriacasAle, name="eliminarAlemanasChecasAustriacasAle"),
     path ("eliminarBelgasFrancesasAle/<belgasFrancesasAle_nombre>/", views.eliminarBelgasFrancesasAle, name="eliminarBelgasFrancesasAle"),
     path ("eliminarBritanicasAle/<britanicasAle_nombre>/", views.eliminarBritanicasAle, name="eliminarBritanicasAle"),
     path ("eliminarInternacionalesAle/<internacionalesAle_nombre>/", views.eliminarInternacionalesAle, name="eliminarInternacionalesAle"),
     path ("eliminarAmericanasLager/<americanasLager_nombre>/", views.eliminarAmericanasLager, name="eliminarAmericanasLager"),
     path ("eliminarAlemanasChecasAustriacasLager/<alemanasChecasAustriacasLager_nombre>/", views.eliminarAlemanasChecasAustriacasLager, name="eliminarAlemanasChecasAustriacasLager"),
     path ("eliminarInternacionalesLager/<internacionalesLager_nombre>/", views.eliminarInternacionalesLager, name="eliminarInternacionalesLager"),
     path ("eliminarOtras/<otras_nombre>/", views.eliminarOtras, name="eliminarOtras"),

     #path ("login", views.login_request, name="login"),
     #path ("register", views.register, name="register"),
     #path ("logout", LogoutView.as_view(template_name="logout.html"), name="logout"),
     #path ("editarPerfil", views.editarPerfil,  name="editarPerfil"),
     #path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),

     path("acercaDeMi/", views.acercaDeMi, name="acercaDeMi"),

]

AppRegistro/urls.py
from django.urls import path, include
from AppFinal import views
from django.contrib.auth.views import LogoutView


app_name="AppRegistro"

urlpatterns = [
    path("", views.inicio, name="inicio"),
    path ("login", views.login_request, name="login"),
    path ("register", views.register, name="register"),
    path ("logout", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path ("editarPerfil", views.editarPerfil,  name="editarPerfil"),
    path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),

]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("AppFinal/", include("AppFinal.urls")),
    path ("AppRegistro/", include("AppRegistro.urls")),
    #path('AppRegistro/', include('AppRegistro.urls', namespace='AppRegistro')),
    #path('AppFinal/', include('AppFinal.urls', namespace='AppFinal')),
] 

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppRegistro/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

AppRegistro/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User





class UserRegisterForm(UserCreationForm):
    email=forms.EmailField()
    password1= forms.CharField (label="Contraseña", widget=forms.PasswordInput)
    password2= forms.CharField (label="Repetir Contraseña", widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ["username", "email", 'password1' , 'password2']
        #help_text = {k:"" for k in fields}

class UserEditForm(UserCreationForm):
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)
    last_name = forms.CharField()
    first_name = forms.CharField()

    class Meta:
        model = User
        fields = ["username", 'email', 'password1', 'password2', 'last_name', 'first_name']
        help_texts = {k:"" for k in fields}

class AvatarFormulario(forms.Form):
     username=forms.ModelChoiceField(queryset=User.objects.all())
     imagen = forms.ImageField(required=True)

     class Meta:
         model= User
         fields= ["imagen"]
         help_texts= {k:"" for k in fields}

AppRegistro/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from AppRegistro.models import  User, Avatar

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from AppRegistro.forms import UserRegisterForm, UserEditForm, AvatarFormulario
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password


@login_required
def inicio(request):
    avatares = Avatar.objects.filter(user=request.user.id)
    url = None
    if avatares:
        url= avatares[0].imagen.url
    return render(request, 'inicio.html', {'url': url})

def login_request(request):
    if request.method== "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contra= form.cleaned_data.get ("password")

            user = authenticate(username=usuario, password=contra)


            if user is not None:
                login(request, user)

                return render (request, "inicio.html", {"mensaje": "Bienvenido {usuario}"})

            else:
                return render (request, "inicio.html", {"mensaje": "Error, datos incorrectos"})

        else:
            return render (request, "inicio.html", {"mensaje": "Error, formulario erroneo"})

    form= AuthenticationForm()

    return render (request, "login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():

            username= form.cleaned_data["username"]
            form.save()
            return render(request, "inicio.html", {"mensaje": "Usuario Creado"})

    else:
        form=UserRegisterForm()

    return render(request, "registro.html", {"form":form})


@login_required
def editarPerfil(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data
            print(miFormulario)
            usuario.email = informacion['email']
            usuario.first_name = informacion['first_name']
            usuario.last_name = informacion['last_name']
            if informacion['password1'] == informacion['password2']:
                usuario.password = make_password(informacion['password1'])
                usuario.save()
            else:
                return render(request, 'inicio.html', {'mensaje':'Contraseña incorrecta.'})

            return render(request, 'inicio.html')
    else:
        miFormulario = UserEditForm(initial={'email':usuario.email})

    return render(request, "editarPerfil.html", {"miFormulario":miFormulario, "usuario":usuario})



@login_required
def agregarAvatar(request):
    if request.method == 'POST':
        miFormulario = AvatarFormulario(request.POST, request.FILES)
        if miFormulario.is_valid():
            avatar_actual = Avatar.objects.filter(user=request.user).first()
            if avatar_actual:
                avatar_actual.imagen = miFormulario.cleaned_data['imagen']
                avatar_actual.save()
            else:
                u = User.objects.get(username=request.user)
                avatar = Avatar(user=u, imagen=miFormulario.cleaned_data['imagen'])
                avatar.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = AvatarFormulario()
    return render(request, 'agregarAvatar.html', {'miFormulario':miFormulario})

AppRegistro/templates/agregarAvatar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Proyecto Final" />
        <meta name="author" content="Matias Escobar" />
        <title>App Final</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="AppFinal/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "AppFinal/css/styles.css"%}"  rel="stylesheet" />

<!-- Masthead-->
        
<header class="masthead">
    <header class="masthead" style="background-image: url('{% static "AppFinal/assets/img/header-bg.jfif"%}')">    </header>
<body>
    <h3>Cargar avatar</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormulario.as_p }}
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>

AppRegistro/templates/editarPerfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AppFinal - Editar Perfil</title>
</head>
<body>
    {% extends "padre.html" %}

    {% load static %}
    
    {% block contenidoQueCambia %}    
     
        <h1>Formulario - Editar Perfil</h1>
        <h1>De {{usuario}}</h1>
            
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
        
            <table>    
                {{ miFormulario.as_table }}    
            </table>    
            <input type="submit", value="Enviar">    
        </form>      
    {% endblock %}        
</body>
</html>

AppRegistro/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Proyecto Final" />
        <meta name="author" content="Matias Escobar" />
        <title>App Final</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="AppFinal/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "AppFinal/css/styles.css"%}"  rel="stylesheet" />

<!-- Masthead-->
        
<header class="masthead">
    <header class="masthead" style="background-image: url('{% static "AppFinal/assets/img/header-bg.jfif"%}')">    </header>


<body>
    <div class="login-form">
        <h1>Login</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }} 
            <button type="submit">Iniciar Sesión</button>
            <button><a href="{% url "AppRegistro:register"%}">Registrarse</a></button>
        </form>
    </div>
</body>
</html>

AppRegistro/templates/logout.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<body>
    <h1>TE HAS DESLOGUEADO..</h1>
</body>
</html>

{% endblock %}

AppRegistro/templates/registro.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Proyecto Final" />
        <meta name="author" content="Matias Escobar" />
        <title>App Final</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="AppFinal/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "AppFinal/css/styles.css"%}"  rel="stylesheet" />

<!-- Masthead-->
        
<header class="masthead">
    <header class="masthead" style="background-image: url('{% static "AppFinal/assets/img/header-bg.jfif"%}')">    </header>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Registrate!</button>
    </form>
</body>
</html>